# Generated by Django 2.2.12 on 2021-02-17 14:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Category of news',
                'db_table': 'news_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_title', models.CharField(blank=True, db_column='title', max_length=120, primary_key=True, serialize=False)),
                ('news_content', ckeditor.fields.RichTextField(blank=True, db_column='content', null=True)),
                ('news_create_time', models.DateTimeField(auto_now=True)),
                ('news_category', models.ManyToManyField(db_column='category', default='', related_name='news_category', to='portal_api.NewsCategory')),
                ('news_main_category', models.ForeignKey(db_column='main_category', on_delete=django.db.models.deletion.CASCADE, related_name='news_main_category', to='portal_api.NewsCategory')),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'managed': True,
            },
        ),
    ]
